vim.keymap.set("n", "<leader>cn", "<cmd>cnext<cr>", { silent = true })
vim.keymap.set("n", "<leader>cp", "<cmd>cprevious<cr>", { silent = true })
vim.keymap.set("n", "<esc><esc>", "<cmd>set hls!<cr>", { silent = true })
vim.keymap.set("n", "<leader>ln", "<cmd>lne<cr>", { silent = true })
vim.keymap.set("n", "<leader>lp", "<cmd>lpr<cr>", { silent = true })
